# Basic Information 
title: Ahmed Abbas
position: Ph.D. Candidate
affiliation: Max Planck Institute for Informatics
affiliation_link: https://www.mpi-inf.mpg.de/
email: ahmed.abbas (at) mpi-inf.mpg.de

# Search Engine Optimization (SEO)
keywords: ahmed abbas, abbas ahmed
canonical: https://www.mpi-inf.mpg.de/~ahabbas/
description: My research work revolves around the intersection of two exciting domains of discrete optimization and deep learning with applications in computer vision and machine learning.

# The option is used to enable the MPI Informatics template.
enable_mpi_logo: false

# The option is used to show the last update time.
enable_last_update: true

# Links
google_scholar: https://scholar.google.com/citations?user=8NzZ7XgAAAAJ
github_link: https://github.com/aabbas90/
linkedin: https://www.linkedin.com/in/ahmed-abbas-65817645/
twitter: https://twitter.com/ahmed_abbas_90/

# Images 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnotes
enable_footnote: true

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# General Data Protection Regulation (GDPR) information
# If you don't need to add the GDPR information, you may remove the following lines.
imprint: https://imprint.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/ahabbas
data_protection: https://data-protection.mpi-klsb.mpg.de/inf/people.mpi-inf.mpg.de/ahabbas?lang=en

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
